### ISSUE TITLE
Mockup: Profile Management / Account

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#10]
![main_page](https://cloud.githubusercontent.com/assets/5320817/15298529/0d161efc-1ba0-11e6-9805-c4685209fdd4.png)
![edit_profile](https://cloud.githubusercontent.com/assets/5320817/15298373/39ff345e-1b9f-11e6-8f81-fec45e5d329f.png)
![delete_profile](https://cloud.githubusercontent.com/assets/5320817/15298375/3a0558f2-1b9f-11e6-93df-c7ea46403f03.png)
![password_profile](https://cloud.githubusercontent.com/assets/5320817/15298376/3a08ae44-1b9f-11e6-9784-625f1d97f0df.png)
![security_profile](https://cloud.githubusercontent.com/assets/5320817/15298374/3a004c40-1b9f-11e6-95ed-3403ff76b561.png)

**Comment by tarekbecker** [comment]
Overview:
- Typically one has one submission, maybe two right? 
- I think links to my submissions overview and my reviews overview would be sufficient 
- I think security question and delete profile is not necessary

**Comment by schnz** [comment]
Based on the Skype talk (17.05.2016) we discussed the following changes:
- First Mockup is discarded. Instead we need two pages to show the own submissions and the papers that must be reviewed in a table
- Second, Third and Forth Mockup should be combined into a single page
  - Field for university selection is missing
  - Dropdown box to toggle email notifications.
- The last Mockup is discarded

**Comment by schnz** [comment]
Closed in favor of #15
