### ISSUE TITLE
Mockup: Reviews

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#11]
![evaluation_submission](https://cloud.githubusercontent.com/assets/5320817/15298430/85ca9720-1b9f-11e6-86ee-b3d95b9773ea.png)
![submission_review_mode](https://cloud.githubusercontent.com/assets/5320817/15298492/d44f7e74-1b9f-11e6-8d54-ab4c0abc4c54.png)

**Comment by tarekbecker** [comment]
Evaluation Submission View:
- I'd like to have a review my review page
- Slider for rating (with explanation)
- Strong / week points should be a textarea not one by one.
- Does this comments section exist?
- Add some text boxes which can be used to give the reviewer some hints by the chair, e.g. do focus on this or please comment on xyz

Overview: see author view feedback

**Comment by schnz** [comment]
Based on the Skype talk (17.05.2016) we discussed the following changes:
- The second mock-up is discarded
  - Alternative: Display the paper as inline PDF document within the page
- The chat is not inherent to the review page, but is present on all pages.
  - Every user can use the chat
- The first mock-up is reached from the "Review" view, where all papers are displayed in a table that require a review (by a specific reviewer). The table contains a button/link wich redirects to the second Mock-up from above (which is the landing page)
- detailed comments is a single textarea
  - As well as major strong points, major weak points, and summary
- The rating _could_ be done as slider or star rating

Furthermore, it is unclear how the review process works
- Is the review for the author, i.e. is it meant as feedback?
- Is the review for the chair, i.e. is it meant to help the chair to decide whether to accept or decline a paper.
- Is it possible to create reviews within the submission phase (Status: open).
