### ISSUE TITLE
Mockup: Submission

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#12]
![submission](https://cloud.githubusercontent.com/assets/5320817/15298461/b2981b92-1b9f-11e6-9e68-98c1fe77506b.png)
![submission_author_mode](https://cloud.githubusercontent.com/assets/5320817/15298468/ba1942ba-1b9f-11e6-93c4-522b65139f7d.png)

**Comment by tarekbecker** [comment]
General:
- I think we should have a "preview" view that shows my submission in order to check if everything that I think I added was added properly (co-authors etc.)

Submission view:
- We should add a "drop pdf file here" zone
- keywords plus/minus buttons are confusing. How do I remove the "computer science" button. 
  - I think something like [this](https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/) would be much better + auto suggestion

Author mode view:
- Do we need a subscribe/unsubscribe per submission? I would add this to the user settings.
- I thought the chat is a way of sending private messages 1:1? Which feature is provided by the play button?
- Which status do exist?
- Purpose of the big textarea in the middle?
- **Proposals**:
  - submission "overview" similar to the submission form. Just add the ability to modify (edit mode like) the submission or withdraw it. 
  - Section underneath the submission that shows the review results. Maybe aggregated or review one by one. Maybe using a [carousel](http://www.w3schools.com/bootstrap/bootstrap_carousel.asp).

**Comment by schnz** [comment]
Based on the Skype talk (17.05.2016) we discussed the following changes:
- The first mock-up is reached from the "submissions" view, where all own submissions are displayed in a table. The table contains a button/link wich redirects to the second Mock-up from above (which is the landing page)
- Co Authors is a freetext multi select field (as suggested by tarek above: https://bootstrap-tagsinput.github.io/bootstrap-tagsinput/examples/)
- Second mock-up is discarded
  - Alternative: Display the paper as inline PDF document within the page

**Comment by schnz** [comment]
Closed in favor of #15
