### ISSUE TITLE
Mockup: Chair / Management

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#13]
![statistics](https://cloud.githubusercontent.com/assets/5320817/15298511/ed2aba12-1b9f-11e6-9525-75974bab4a7e.png)
![management_1](https://cloud.githubusercontent.com/assets/5320817/15298519/fb7e25fe-1b9f-11e6-9828-ebf2fd70dfaf.png)
![management_2](https://cloud.githubusercontent.com/assets/5320817/15298520/fb99ad06-1b9f-11e6-8f26-0ec3e2093c00.png)
![management_3](https://cloud.githubusercontent.com/assets/5320817/15298521/fba97088-1b9f-11e6-8698-7ddaf7c4f43d.png)

**Comment by tarekbecker** [comment]
These views are somehow confusing for me:
- How do I get to view Part 2 from Part 1?
- Why can I assign new chairs to individual papers? Why does a submission deadline exists for a single paper? Purpose of plus/minus?
- Part 3: Why do we have schedules for each individual paper?

**Comment by schnz** [comment]
Based on the Skype talk (17.05.2016) we discussed the following changes:
- All pages are only accessable by the chair
- The type of charts to be displayed need to be discussed
- The second mock-up needs to be splitted into individual pages (one for each category)
  - The individual pages display a table (maybe with pagination) and link to detail view
  - A single user page (not one for each role)! The table shows the roles of the user
- Management (Part 2):
  - Checkboxes are discarded completly 
  - Detailview for Paper name, Author, Reviewer and Reviews
  - Deadlines are not inherent to paper (but to a conference)
  - We need an additional view (settings) which allows to configure the submission/review phases.
    - Allow to force open a phase.
- Additionally, a new view is needed which shows a table of all submitted papers. A row within the table allows the assignment of reviewers (e.g. with the [select2](https://select2.github.io/examples.html#multiple) plugin)

**Comment by schnz** [comment]
Closed in favor of #15.
