### ISSUE TITLE
Mockup: Login / Signup / Landing Page

### ISSUE THREAD

**Issue by tarekbecker** [tkpraktikum/tkpraktikum#9]
![login](https://cloud.githubusercontent.com/assets/5320817/15298248/b061e9b2-1b9e-11e6-98d2-f510efd31bad.png)
- Sign up page follows
- Open Questions
  - Do we want to have a header and/or footer

**Comment by schnz** [comment]
If we are going to support login via HTTPS it would be easier to have a login page with a very simple template (without footer/header) as we need to ensure that every site element is delivered over HTTPS (including background images and (external) scripts).
On the other hand, if that is possible I would prefer the embed the login page into the application default template (similar to this: https://cms-assets.tutsplus.com/uploads/users/317/posts/23489/image/register.jpg)

**Comment by schnz** [comment]
Based on the Skype talk (17.05.2016) we discussed the following changes:
- Use a header/footer (but make sure everything is delivered via HTTPS)
- Convert the "Sign In" button to a "Register" _link_
- Mock up for Register page is missing, but the register page should also be a single formular containing all necessary fields (single column layout)
  - Optionally a password strength indicator field
  - Required field: University affiliation selection

**Comment by schnz** [comment]
Closed. Merged open points into #15.
